### ISSUE TITLE
Unable to get image data from canvas because the canvas has been tainted by cross-origin data.

### ISSUE THREAD

**Issue by kanakiyajay** [pbakaus/domvas#4]
After loading the dom-image in the canvas you cannot use getImagedata 
Is there any way to get the pure image data ?

**Comment by pbakaus** [comment]
Unfortunately not, due to a weird bug in browsers :/  Any base64 SVG url that gets painted onto a canvas renders the canvas "tainted", so unless the browsers fix this, I can't do anything about it. I have open tickets, but no success so far :(
